import { describe, expect, it } from "vitest";
import { generateContextPack } from "./generate";
import type { Proposal, SpecForgeDataStore } from "../types";
import type { ServiceFeature, FunctionalFeature } from "../features";

const scope = { applicationServiceId: "service-a", scopePath: "family/product/module/service-a" };
const service = { id: "sf-a", name: "Design assistance", description: "A governed design service", lifecycleStatus: "ACTIVE", tags: [], actors: ["Architect"], scenario: "Create a design", valueOutcome: "A traceable design", benefitHypothesis: "Reduce drift", serviceBoundary: ["Design"], acceptanceCriteria: ["Reviewable"], architectureScope: scope, localizedContent: { zh: { name: "设计辅助", description: "受治理的设计服务", actors: ["架构师"], scenario: "创建设计", valueOutcome: "可追溯设计", benefitHypothesis: "减少漂移", serviceBoundary: ["设计"], acceptanceCriteria: ["可评审"] } }, createdAt: "2026-09-05T00:00:00.000Z", updatedAt: "2026-09-05T00:00:00.000Z" } as unknown as ServiceFeature;
const functional = { id: "ff-a", name: "Validate design", description: "Validate a design", lifecycleStatus: "ACTIVE", tags: [], trigger: "Submit", observableBehavior: "Returns validation", preconditions: [], postconditions: [], exceptionBehaviors: [], acceptanceCriteria: ["Returns a result"], architectureScope: scope, localizedContent: { zh: { name: "校验设计", description: "校验设计", trigger: "提交", observableBehavior: "返回校验结果", preconditions: [], postconditions: [], exceptionBehaviors: [], acceptanceCriteria: ["返回结果"] } }, createdAt: "2026-09-05T00:00:00.000Z", updatedAt: "2026-09-05T00:00:00.000Z" } as unknown as FunctionalFeature;
const proposal = { id: "proposal-feature-pack", name: "Feature pack", title: "Feature pack", description: "Proposal description", background: "Background", goal: "Goal", nonGoal: "Non goal", scope: "Feature scope", risks: [], impactedAssets: [{ type: "serviceFeature", id: "sf-a", label: service.name }, { type: "functionalFeature", id: "ff-a", label: functional.name }], specChanges: [], implementationTasks: [], rolloutPlan: "Roll out", rollbackPlan: "Roll back", status: "reviewing", createdAt: service.createdAt, updatedAt: service.updatedAt, architectureScope: scope, localizedContent: { zh: { name: "特性包", title: "特性包", description: "提案描述", background: "背景", goal: "目标", nonGoal: "非目标", scope: "特性范围", risks: [], specChanges: [], rolloutPlan: "发布", rollbackPlan: "回滚" } } } as unknown as Proposal;
const catalog = { domains: [], dataModels: [], apis: [], events: [], businessRules: [], stateMachines: [], integrations: [], qualityRequirements: [], observabilityDesigns: [], adrs: [], proposals: [proposal], contextPacks: [], serviceFeatures: [service], functionalFeatures: [functional] } as unknown as SpecForgeDataStore;

describe("Feature context pack sections", () => { it("renders service and functional sections in both locales", async () => { const pack = await generateContextPack(proposal.id, { catalog, locale: "en" }); expect(pack.generatedMarkdown).toContain("## 1. Service Features"); expect(pack.generatedMarkdown).toContain("## 2. Functional Features"); expect(pack.localizedContent?.zh?.generatedMarkdown).toContain("## 1. 服务特性"); expect(pack.localizedContent?.zh?.generatedMarkdown).toContain("## 2. 功能特性"); }); });
