import { PrismaClient } from "@prisma/client";
import type { ArchitectureMapBudget, ArchitectureMapIdentity, ArchitectureScopeRef, ArchitectureUnitFilter, ArchitectureUnitMappingProjection, ArchitectureUnitMemberProjection, ArchitectureUnitProjection, ArchitectureUnitProjectionPage, KnowledgeProjectionEdge, KnowledgeProjectionNode, ProjectionManifestV2 } from "@specforge/core";
import type { ArchitectureFactSource, ArchitectureMapQueryRepository, ArchitectureUnitPageCursor, PublishedBaselineSummary, ThreeAQueryRepository } from "./types";

export class PrismaThreeAQueryRepository implements ThreeAQueryRepository, ArchitectureMapQueryRepository {
  constructor(private readonly prisma: PrismaClient) {}
  async listOfficialBaselines(scope: ArchitectureScopeRef): Promise<PublishedBaselineSummary[]> { const rows = await this.prisma.knowledgeBaseline.findMany({ where: { ...scope, status: { in: ["PUBLISHED", "SUPERSEDED"] }, publishedAt: { not: null } }, orderBy: [{ publishedAt: "desc" }, { id: "asc" }] }); return rows.map((row) => ({ ...scope, id: row.id, streamId: row.streamId, changeSetId: row.changeSetId, status: row.status as "PUBLISHED" | "SUPERSEDED", publishedAt: row.publishedAt!.toISOString() })); }
  async listPublishedManifests(scope: ArchitectureScopeRef, baselineId: string): Promise<ProjectionManifestV2[]> { const rows = await this.prisma.projectionManifest.findMany({ where: { ...scope, baselineId, projectionSchemaVersion: "3a.v2", publishedAt: { not: null }, profileId: { not: null }, profileVersion: { not: null }, generationId: { not: null }, inputDigest: { not: null }, contentDigest: { not: null }, nodeCount: { not: null }, edgeCount: { not: null } }, orderBy: [{ publishedAt: "desc" }, { id: "asc" }] }); return rows.map(manifestFromRow); }
  async searchNodes(scope: ArchitectureScopeRef, manifest: ProjectionManifestV2, input: { query?: string; layer?: "BIZ" | "SYS" | "TECH"; afterSortKey?: string; limit: number }): Promise<{ nodes: KnowledgeProjectionNode[]; hasMore: boolean }> { const rows = await this.prisma.knowledgeProjectionNode.findMany({ where: { ...scope, generationId: manifest.generationId, ...(input.layer ? { layer: input.layer } : {}), ...(input.query ? { semanticIdentity: { contains: input.query, mode: "insensitive" } } : {}), ...(input.afterSortKey ? { sortKey: { gt: input.afterSortKey } } : {}) }, orderBy: [{ sortKey: "asc" }, { assertionId: "asc" }], take: input.limit + 1 }); return { nodes: rows.slice(0, input.limit).map(nodeFromRow), hasMore: rows.length > input.limit }; }
  async getFact(scope: ArchitectureScopeRef, manifest: ProjectionManifestV2, assertionId: string): Promise<ArchitectureFactSource | undefined> { const node = await this.prisma.knowledgeProjectionNode.findUnique({ where: { applicationServiceId_scopePath_generationId_assertionId: { ...scope, generationId: manifest.generationId, assertionId } } }); if (!node) return undefined; const assertion = await this.prisma.knowledgeAssertion.findUnique({ where: { applicationServiceId_scopePath_id: { ...scope, id: assertionId } } }); return factSource(nodeFromRow(node), assertion); }
  async getFactsByIds(scope: ArchitectureScopeRef, manifest: ProjectionManifestV2, assertionIds: string[]): Promise<ArchitectureFactSource[]> {
    const uniqueIds = [...new Set(assertionIds)].sort();
    if (!uniqueIds.length) return [];
    const nodes = await this.prisma.knowledgeProjectionNode.findMany({ where: { ...scope, generationId: manifest.generationId, assertionId: { in: uniqueIds } }, orderBy: [{ sortKey: "asc" }, { assertionId: "asc" }] });
    const assertions = await this.prisma.knowledgeAssertion.findMany({ where: { ...scope, id: { in: nodes.map((item) => item.assertionId) } } });
    const assertionById = new Map(assertions.map((item) => [item.id, item]));
    return nodes.map((item) => factSource(nodeFromRow(item), assertionById.get(item.assertionId)));
  }
  async listAdjacentEdges(scope: ArchitectureScopeRef, manifest: ProjectionManifestV2, input: { frontierAssertionIds: string[]; direction: "upstream" | "downstream" | "both"; relationTypes?: string[]; limit: number }): Promise<{ edges: KnowledgeProjectionEdge[]; hasMore: boolean }> {
    const frontier = [...new Set(input.frontierAssertionIds)].sort();
    if (!frontier.length) return { edges: [], hasMore: false };
    const directional = input.direction === "downstream"
      ? { sourceAssertionId: { in: frontier } }
      : input.direction === "upstream"
        ? { targetAssertionId: { in: frontier } }
        : { OR: [{ sourceAssertionId: { in: frontier } }, { targetAssertionId: { in: frontier } }] };
    const rows = await this.prisma.knowledgeProjectionEdge.findMany({ where: { ...scope, generationId: manifest.generationId, ...directional, ...(input.relationTypes?.length ? { relationCode: { in: input.relationTypes } } : {}) }, orderBy: [{ sourceAssertionId: "asc" }, { targetAssertionId: "asc" }, { relationshipIdentity: "asc" }], take: input.limit + 1 });
    return { edges: rows.slice(0, input.limit).map(edgeFromRow), hasMore: rows.length > input.limit };
  }
  async listEdges(scope: ArchitectureScopeRef, manifest: ProjectionManifestV2, input: { assertionId?: string; limit?: number } = {}): Promise<KnowledgeProjectionEdge[]> { const rows = await this.prisma.knowledgeProjectionEdge.findMany({ where: { ...scope, generationId: manifest.generationId, ...(input.assertionId ? { OR: [{ sourceAssertionId: input.assertionId }, { targetAssertionId: input.assertionId }] } : {}) }, orderBy: [{ sourceAssertionId: "asc" }, { targetAssertionId: "asc" }, { relationshipIdentity: "asc" }], ...(input.limit === undefined ? {} : { take: input.limit }) }); return rows.map(edgeFromRow); }
  async listArchitectureUnits(identity: ArchitectureMapIdentity, filter: ArchitectureUnitFilter, budget: ArchitectureMapBudget, cursor: ArchitectureUnitPageCursor): Promise<{ units: ArchitectureUnitProjection[]; totalByLayer: Record<"BIZ" | "SYS" | "TECH", number>; unclassifiedCount: number; nextCursor?: ArchitectureUnitPageCursor }> {
    const where: Record<string, unknown> = { ...identity };
    if (filter.kinds?.length) where.kind = { in: filter.kinds };
    if (filter.minCriticality !== undefined) where.criticality = { gte: filter.minCriticality };
    if (filter.minCompleteness !== undefined) where.completeness = { gte: filter.minCompleteness };
    if (filter.includeUnclassified === false) where.unclassifiedMemberCount = 0;
    if (filter.query?.trim()) where.OR = [{ unitIdentity: { contains: filter.query.trim(), mode: "insensitive" } }, { canonicalName: { contains: filter.query.trim(), mode: "insensitive" } }];
    const layerNames = ["BIZ", "SYS", "TECH"] as const;
    const counts = await Promise.all(layerNames.map(async (layer) => [layer, await this.prisma.architectureUnitProjection.count({ where: { ...where, layer } })] as const));
    const rowsByLayer = await Promise.all(layerNames.map(async (layer) => this.prisma.architectureUnitProjection.findMany({ where: { ...where, layer }, orderBy: [{ parentUnitIdentity: "asc" }, { criticality: "desc" }, { canonicalName: "asc" }, { unitIdentity: "asc" }], skip: cursor[layer], take: budget.maxUnitsPerLayer + 1 })));
    const hasMore = rowsByLayer.some((rows) => rows.length > budget.maxUnitsPerLayer);
    const units = rowsByLayer.flatMap((rows) => rows.slice(0, budget.maxUnitsPerLayer).map(architectureUnitFromRow)).sort(compareArchitectureUnits);
    const nextCursor = hasMore ? { BIZ: cursor.BIZ + Math.min(budget.maxUnitsPerLayer, rowsByLayer[0]!.length), SYS: cursor.SYS + Math.min(budget.maxUnitsPerLayer, rowsByLayer[1]!.length), TECH: cursor.TECH + Math.min(budget.maxUnitsPerLayer, rowsByLayer[2]!.length) } : undefined;
    const totalByLayer = Object.fromEntries(counts) as Record<"BIZ" | "SYS" | "TECH", number>;
    const unclassifiedCount = await this.prisma.architectureUnitProjection.count({ where: { ...identity, unclassifiedMemberCount: { gt: 0 } } });
    return { units, totalByLayer, unclassifiedCount, ...(nextCursor ? { nextCursor } : {}) };
  }
  async getArchitectureUnitsByIdentity(identity: ArchitectureMapIdentity, unitIdentities: string[]): Promise<ArchitectureUnitProjection[]> { if (!unitIdentities.length) return []; const rows = await this.prisma.architectureUnitProjection.findMany({ where: { ...identity, unitIdentity: { in: [...new Set(unitIdentities)] } }, orderBy: [{ parentUnitIdentity: "asc" }, { criticality: "desc" }, { canonicalName: "asc" }, { unitIdentity: "asc" }] }); return rows.map(architectureUnitFromRow); }
  async listArchitectureUnitMembers(identity: ArchitectureMapIdentity, unitIdentity: string, limit: number, assetTypes?: string[], offset = 0): Promise<{ members: ArchitectureUnitMemberProjection[]; hasMore: boolean }> { const rows = await this.prisma.architectureUnitMemberProjection.findMany({ where: { ...identity, unitIdentity, ...(assetTypes?.length ? { assetType: { in: assetTypes } } : {}) }, orderBy: [{ semanticIdentity: "asc" }, { assertionId: "asc" }], skip: offset, take: limit + 1 }); return { members: rows.slice(0, limit).map(architectureUnitMemberFromRow), hasMore: rows.length > limit }; }
  async listArchitectureUnitMembersByUnits(identity: ArchitectureMapIdentity, unitIdentities: string[], limit: number): Promise<{ members: ArchitectureUnitMemberProjection[]; hasMore: boolean }> {
    const ids = [...new Set(unitIdentities)].filter((id) => id.startsWith("unit:")).sort();
    if (!ids.length) return { members: [], hasMore: false };
    const rows = await this.prisma.architectureUnitMemberProjection.findMany({
      where: { ...identity, unitIdentity: { in: ids } },
      orderBy: [{ unitIdentity: "asc" }, { semanticIdentity: "asc" }, { assertionId: "asc" }],
      take: limit + 1
    });
    return { members: rows.slice(0, limit).map(architectureUnitMemberFromRow), hasMore: rows.length > limit };
  }
  async listArchitectureUnitMappings(identity: ArchitectureMapIdentity, unitIdentities: string[], limit: number, mappingFamilies?: string[], offset = 0): Promise<{ mappings: ArchitectureUnitMappingProjection[]; hasMore: boolean }> { const ids = [...new Set(unitIdentities)].filter((id) => id.startsWith("unit:")); if (!ids.length) return { mappings: [], hasMore: false }; const rows = await this.prisma.architectureUnitMappingProjection.findMany({ where: { ...identity, ...(mappingFamilies?.length ? { mappingFamily: { in: mappingFamilies } } : {}), sourceUnitIdentity: { in: ids }, targetUnitIdentity: { in: ids } }, orderBy: [{ sourceUnitIdentity: "asc" }, { targetUnitIdentity: "asc" }, { mappingFamily: "asc" }, { mappingIdentity: "asc" }], skip: offset, take: limit + 1 }); return { mappings: rows.slice(0, limit).map(architectureUnitMappingFromRow), hasMore: rows.length > limit }; }
  async listArchitectureUnitNeighborhoodMappings(identity: ArchitectureMapIdentity, frontierUnitIdentities: string[], direction: "upstream" | "downstream" | "both", limit: number, mappingFamilies?: string[]): Promise<{ mappings: ArchitectureUnitMappingProjection[]; hasMore: boolean }> { const ids = [...new Set(frontierUnitIdentities)]; const directionWhere = direction === "upstream" ? { targetUnitIdentity: { in: ids } } : direction === "downstream" ? { sourceUnitIdentity: { in: ids } } : { OR: [{ sourceUnitIdentity: { in: ids } }, { targetUnitIdentity: { in: ids } }] }; const rows = await this.prisma.architectureUnitMappingProjection.findMany({ where: { ...identity, ...directionWhere, ...(mappingFamilies?.length ? { mappingFamily: { in: mappingFamilies } } : {}) }, orderBy: [{ sourceUnitIdentity: "asc" }, { targetUnitIdentity: "asc" }, { mappingFamily: "asc" }, { mappingIdentity: "asc" }], take: limit + 1 }); return { mappings: rows.slice(0, limit).map(architectureUnitMappingFromRow), hasMore: rows.length > limit }; }
  async listSameLayerDependencies(identity: ArchitectureMapIdentity, assertionIds: string[], limit: number): Promise<{ edges: KnowledgeProjectionEdge[]; hasMore: boolean }> { if (!assertionIds.length) return { edges: [], hasMore: false }; const { projectionManifestId: _projectionManifestId, ...edgeIdentity } = identity; const rows = await this.prisma.knowledgeProjectionEdge.findMany({ where: { ...edgeIdentity, OR: [{ sourceAssertionId: { in: assertionIds }, targetAssertionId: { in: assertionIds } }] }, orderBy: [{ sourceAssertionId: "asc" }, { targetAssertionId: "asc" }, { relationCode: "asc" }, { relationshipIdentity: "asc" }], take: limit + 1 }); return { edges: rows.slice(0, limit).map(edgeFromRow), hasMore: rows.length > limit }; }
}
function manifestFromRow(row: any): ProjectionManifestV2 { return { applicationServiceId: row.applicationServiceId, scopePath: row.scopePath, id: row.id, baselineId: row.baselineId, generationId: row.generationId, profileId: row.profileId, profileVersion: row.profileVersion, projectionSchemaVersion: "3a.v2", sourceRevisionIds: row.sourceRevisionIds as string[], relationshipVersion: row.relationshipVersion, query: row.query as Record<string, unknown>, inputDigest: row.inputDigest, contentDigest: row.contentDigest, nodeCount: row.nodeCount, edgeCount: row.edgeCount, publishedAt: row.publishedAt.toISOString() }; }
function nodeFromRow(row: any): KnowledgeProjectionNode { return { applicationServiceId: row.applicationServiceId, scopePath: row.scopePath, generationId: row.generationId, baselineId: row.baselineId, assertionId: row.assertionId, semanticIdentity: row.semanticIdentity, layer: row.layer, sortKey: row.sortKey, ...(row.acceptedAssetType ? { acceptedAssetType: row.acceptedAssetType } : {}), ...(row.acceptedAssetId ? { acceptedAssetId: row.acceptedAssetId } : {}), contentDigest: row.contentDigest }; }
function edgeFromRow(row: any): KnowledgeProjectionEdge { return { applicationServiceId: row.applicationServiceId, scopePath: row.scopePath, generationId: row.generationId, baselineId: row.baselineId, relationshipIdentity: row.relationshipIdentity, ...(row.relationshipAssertionId ? { relationshipAssertionId: row.relationshipAssertionId } : {}), ...(row.relationshipEventId ? { relationshipEventId: row.relationshipEventId } : {}), sourceAssertionId: row.sourceAssertionId, targetAssertionId: row.targetAssertionId, sourceSemanticIdentity: row.sourceSemanticIdentity, targetSemanticIdentity: row.targetSemanticIdentity, relationCode: row.relationCode, confidence: row.confidence, relationshipVersion: row.relationshipVersion, contentDigest: row.contentDigest }; }
function factSource(node: KnowledgeProjectionNode, assertion: any): ArchitectureFactSource { return { node, factType: assertion?.factType, aspect: assertion?.aspect, confidence: assertion?.confidence, status: assertion?.status, value: assertion?.value as Record<string, unknown> | undefined, evidenceRefs: arrayOfStrings(assertion?.evidenceRefs), sourceObservationIds: arrayOfStrings(assertion?.sourceObservationIds), unresolvedQuestions: arrayOfStrings(assertion?.unresolvedQuestions), counterEvidence: arrayOfStrings(assertion?.counterEvidence) }; }
function arrayOfStrings(value: unknown): string[] { return Array.isArray(value) ? value.filter((item): item is string => typeof item === "string") : []; }
function architectureUnitFromRow(row: any): ArchitectureUnitProjection { return { applicationServiceId: row.applicationServiceId, scopePath: row.scopePath, generationId: row.generationId, baselineId: row.baselineId, projectionManifestId: row.projectionManifestId, unitIdentity: row.unitIdentity, layer: row.layer, kind: row.kind, ...(row.parentUnitIdentity ? { parentUnitIdentity: row.parentUnitIdentity } : {}), canonicalName: row.canonicalName, ...(typeof row.localizedName === "string" ? { localizedName: row.localizedName } : {}), aliases: Array.isArray(row.aliases) ? row.aliases.filter((item: unknown): item is string => typeof item === "string") : [], memberCount: row.memberCount, criticality: row.criticality, completeness: row.completeness, evidenceCount: row.evidenceCount, unclassifiedMemberCount: row.unclassifiedMemberCount, contentDigest: row.contentDigest }; }
function architectureUnitMemberFromRow(row: any): ArchitectureUnitMemberProjection { return { applicationServiceId: row.applicationServiceId, scopePath: row.scopePath, generationId: row.generationId, baselineId: row.baselineId, projectionManifestId: row.projectionManifestId, unitIdentity: row.unitIdentity, assertionId: row.assertionId, ...(row.assetType ? { assetType: row.assetType } : {}), semanticIdentity: row.semanticIdentity, contentDigest: row.contentDigest }; }
function architectureUnitMappingFromRow(row: any): ArchitectureUnitMappingProjection { return { applicationServiceId: row.applicationServiceId, scopePath: row.scopePath, generationId: row.generationId, baselineId: row.baselineId, projectionManifestId: row.projectionManifestId, mappingIdentity: row.mappingIdentity, sourceUnitIdentity: row.sourceUnitIdentity, targetUnitIdentity: row.targetUnitIdentity, sourceLayer: row.sourceLayer, targetLayer: row.targetLayer, mappingFamily: row.mappingFamily, relationshipCount: row.relationshipCount, evidenceCount: row.evidenceCount, confidence: row.confidence, contentDigest: row.contentDigest }; }
function compareArchitectureUnits(left: ArchitectureUnitProjection, right: ArchitectureUnitProjection): number { return (left.parentUnitIdentity ?? "").localeCompare(right.parentUnitIdentity ?? "", "en") || right.criticality - left.criticality || left.canonicalName.localeCompare(right.canonicalName, "en") || left.unitIdentity.localeCompare(right.unitIdentity, "en"); }
