import { PrismaClient } from "@prisma/client";
import type { ArchitectureScopeRef, KnowledgeProjectionEdge, KnowledgeProjectionNode, ProjectionManifestV2 } from "@specforge/core";
import type { ArchitectureFactSource, PublishedBaselineSummary, ThreeAQueryRepository } from "./types";

export class PrismaThreeAQueryRepository implements ThreeAQueryRepository {
  constructor(private readonly prisma: PrismaClient) {}
  async listOfficialBaselines(scope: ArchitectureScopeRef): Promise<PublishedBaselineSummary[]> { const rows = await this.prisma.knowledgeBaseline.findMany({ where: { ...scope, status: { in: ["PUBLISHED", "SUPERSEDED"] }, publishedAt: { not: null } }, orderBy: [{ publishedAt: "desc" }, { id: "asc" }] }); return rows.map((row) => ({ ...scope, id: row.id, streamId: row.streamId, changeSetId: row.changeSetId, status: row.status as "PUBLISHED" | "SUPERSEDED", publishedAt: row.publishedAt!.toISOString() })); }
  async listPublishedManifests(scope: ArchitectureScopeRef, baselineId: string): Promise<ProjectionManifestV2[]> { const rows = await this.prisma.projectionManifest.findMany({ where: { ...scope, baselineId, projectionSchemaVersion: "3a.v2", publishedAt: { not: null }, profileId: { not: null }, profileVersion: { not: null }, generationId: { not: null }, inputDigest: { not: null }, contentDigest: { not: null }, nodeCount: { not: null }, edgeCount: { not: null } }, orderBy: [{ publishedAt: "desc" }, { id: "asc" }] }); return rows.map(manifestFromRow); }
  async searchNodes(scope: ArchitectureScopeRef, manifest: ProjectionManifestV2, input: { query?: string; layer?: "BIZ" | "SYS" | "TECH"; afterSortKey?: string; limit: number }): Promise<{ nodes: KnowledgeProjectionNode[]; hasMore: boolean }> { const rows = await this.prisma.knowledgeProjectionNode.findMany({ where: { ...scope, generationId: manifest.generationId, ...(input.layer ? { layer: input.layer } : {}), ...(input.query ? { semanticIdentity: { contains: input.query, mode: "insensitive" } } : {}), ...(input.afterSortKey ? { sortKey: { gt: input.afterSortKey } } : {}) }, orderBy: [{ sortKey: "asc" }, { assertionId: "asc" }], take: input.limit + 1 }); return { nodes: rows.slice(0, input.limit).map(nodeFromRow), hasMore: rows.length > input.limit }; }
  async getFact(scope: ArchitectureScopeRef, manifest: ProjectionManifestV2, assertionId: string): Promise<ArchitectureFactSource | undefined> { const node = await this.prisma.knowledgeProjectionNode.findUnique({ where: { applicationServiceId_scopePath_generationId_assertionId: { ...scope, generationId: manifest.generationId, assertionId } } }); if (!node) return undefined; const assertion = await this.prisma.knowledgeAssertion.findUnique({ where: { applicationServiceId_scopePath_id: { ...scope, id: assertionId } } }); return factSource(nodeFromRow(node), assertion); }
  async getFactsByIds(scope: ArchitectureScopeRef, manifest: ProjectionManifestV2, assertionIds: string[]): Promise<ArchitectureFactSource[]> {
    const uniqueIds = [...new Set(assertionIds)].sort();
    if (!uniqueIds.length) return [];
    const nodes = await this.prisma.knowledgeProjectionNode.findMany({ where: { ...scope, generationId: manifest.generationId, assertionId: { in: uniqueIds } }, orderBy: [{ sortKey: "asc" }, { assertionId: "asc" }] });
    const assertions = await this.prisma.knowledgeAssertion.findMany({ where: { ...scope, id: { in: nodes.map((item) => item.assertionId) } } });
    const assertionById = new Map(assertions.map((item) => [item.id, item]));
    return nodes.map((item) => factSource(nodeFromRow(item), assertionById.get(item.assertionId)));
  }
  async listAdjacentEdges(scope: ArchitectureScopeRef, manifest: ProjectionManifestV2, input: { frontierAssertionIds: string[]; direction: "upstream" | "downstream" | "both"; relationTypes?: string[]; limit: number }): Promise<{ edges: KnowledgeProjectionEdge[]; hasMore: boolean }> {
    const frontier = [...new Set(input.frontierAssertionIds)].sort();
    if (!frontier.length) return { edges: [], hasMore: false };
    const directional = input.direction === "downstream"
      ? { sourceAssertionId: { in: frontier } }
      : input.direction === "upstream"
        ? { targetAssertionId: { in: frontier } }
        : { OR: [{ sourceAssertionId: { in: frontier } }, { targetAssertionId: { in: frontier } }] };
    const rows = await this.prisma.knowledgeProjectionEdge.findMany({ where: { ...scope, generationId: manifest.generationId, ...directional, ...(input.relationTypes?.length ? { relationCode: { in: input.relationTypes } } : {}) }, orderBy: [{ sourceAssertionId: "asc" }, { targetAssertionId: "asc" }, { relationshipIdentity: "asc" }], take: input.limit + 1 });
    return { edges: rows.slice(0, input.limit).map(edgeFromRow), hasMore: rows.length > input.limit };
  }
  async listEdges(scope: ArchitectureScopeRef, manifest: ProjectionManifestV2, input: { assertionId?: string; limit?: number } = {}): Promise<KnowledgeProjectionEdge[]> { const rows = await this.prisma.knowledgeProjectionEdge.findMany({ where: { ...scope, generationId: manifest.generationId, ...(input.assertionId ? { OR: [{ sourceAssertionId: input.assertionId }, { targetAssertionId: input.assertionId }] } : {}) }, orderBy: [{ sourceAssertionId: "asc" }, { targetAssertionId: "asc" }, { relationshipIdentity: "asc" }], ...(input.limit === undefined ? {} : { take: input.limit }) }); return rows.map(edgeFromRow); }
}
function manifestFromRow(row: any): ProjectionManifestV2 { return { applicationServiceId: row.applicationServiceId, scopePath: row.scopePath, id: row.id, baselineId: row.baselineId, generationId: row.generationId, profileId: row.profileId, profileVersion: row.profileVersion, projectionSchemaVersion: "3a.v2", sourceRevisionIds: row.sourceRevisionIds as string[], relationshipVersion: row.relationshipVersion, query: row.query as Record<string, unknown>, inputDigest: row.inputDigest, contentDigest: row.contentDigest, nodeCount: row.nodeCount, edgeCount: row.edgeCount, publishedAt: row.publishedAt.toISOString() }; }
function nodeFromRow(row: any): KnowledgeProjectionNode { return { applicationServiceId: row.applicationServiceId, scopePath: row.scopePath, generationId: row.generationId, baselineId: row.baselineId, assertionId: row.assertionId, semanticIdentity: row.semanticIdentity, layer: row.layer, sortKey: row.sortKey, ...(row.acceptedAssetType ? { acceptedAssetType: row.acceptedAssetType } : {}), ...(row.acceptedAssetId ? { acceptedAssetId: row.acceptedAssetId } : {}), contentDigest: row.contentDigest }; }
function edgeFromRow(row: any): KnowledgeProjectionEdge { return { applicationServiceId: row.applicationServiceId, scopePath: row.scopePath, generationId: row.generationId, baselineId: row.baselineId, relationshipIdentity: row.relationshipIdentity, ...(row.relationshipAssertionId ? { relationshipAssertionId: row.relationshipAssertionId } : {}), ...(row.relationshipEventId ? { relationshipEventId: row.relationshipEventId } : {}), sourceAssertionId: row.sourceAssertionId, targetAssertionId: row.targetAssertionId, sourceSemanticIdentity: row.sourceSemanticIdentity, targetSemanticIdentity: row.targetSemanticIdentity, relationCode: row.relationCode, confidence: row.confidence, relationshipVersion: row.relationshipVersion, contentDigest: row.contentDigest }; }
function factSource(node: KnowledgeProjectionNode, assertion: any): ArchitectureFactSource { return { node, factType: assertion?.factType, aspect: assertion?.aspect, confidence: assertion?.confidence, status: assertion?.status, value: assertion?.value as Record<string, unknown> | undefined, evidenceRefs: arrayOfStrings(assertion?.evidenceRefs), sourceObservationIds: arrayOfStrings(assertion?.sourceObservationIds), unresolvedQuestions: arrayOfStrings(assertion?.unresolvedQuestions), counterEvidence: arrayOfStrings(assertion?.counterEvidence) }; }
function arrayOfStrings(value: unknown): string[] { return Array.isArray(value) ? value.filter((item): item is string => typeof item === "string") : []; }
