"use client";

import type { ArchitectureUnitFilter, ArchitectureUnitKind } from "@specforge/core";
import { RotateCcw, Search } from "lucide-react";
import { T } from "../language-provider";

const kinds: ArchitectureUnitKind[] = ["CAPABILITY", "PROCESS", "BUSINESS_OBJECT", "APPLICATION", "SERVICE", "COMPONENT", "DATA_DOMAIN", "PLATFORM", "RUNTIME", "INFRASTRUCTURE", "TECHNOLOGY_SERVICE"];

export function ArchitectureMapFilterBar({ value, onChange }: { value: ArchitectureUnitFilter; onChange: (value: ArchitectureUnitFilter) => void }) {
  const toggleLayer = (layer: "BIZ" | "SYS" | "TECH") => onChange({ ...value, layers: value.layers?.includes(layer) ? value.layers.filter((item) => item !== layer) : [...(value.layers ?? []), layer] });
  return <div className="space-y-3 rounded-lg border border-border bg-white p-3 shadow-panel" data-testid="architecture-map-filters">
    <div className="flex flex-wrap items-center gap-2"><span className="text-xs font-semibold text-muted"><T k="threeA.mapFilters" /></span><label className="relative min-w-[16rem] flex-1"><Search className="pointer-events-none absolute left-2.5 top-2 text-muted" size={14} /><span className="sr-only"><T k="threeA.mapSearch" /></span><input aria-label="Search architecture units" className="h-8 w-full rounded-md border border-border pl-8 pr-2 text-xs" placeholder="orders, policy..." value={value.query ?? ""} onChange={(event) => onChange({ ...value, query: event.target.value || undefined })} /></label><button aria-label="Reset map filters" className="inline-flex h-8 items-center gap-1 rounded-md border border-border px-2 text-xs font-semibold" onClick={() => onChange({})} type="button"><RotateCcw size={13} /><T k="threeA.resetGraph" /></button></div>
    <div className="flex flex-wrap items-center gap-2 text-xs"><span className="font-semibold text-muted"><T k="threeA.mapLayers" /></span>{(["BIZ", "SYS", "TECH"] as const).map((layer) => <button aria-pressed={value.layers?.includes(layer) ?? false} className={"rounded-full border px-2 py-1 font-semibold " + (value.layers?.includes(layer) ? "border-accent bg-blue-50 text-accent" : "border-border text-muted")} key={layer} onClick={() => toggleLayer(layer)} type="button">{layer}</button>)}<label className="ml-2 flex items-center gap-1"><T k="threeA.minCompleteness" /><input className="h-7 w-16 rounded border border-border px-1" max="1" min="0" onChange={(event) => onChange({ ...value, minCompleteness: event.target.value ? Number(event.target.value) : undefined })} step=".1" type="number" value={value.minCompleteness ?? ""} /></label><label className="flex items-center gap-1"><T k="threeA.minCriticality" /><input className="h-7 w-16 rounded border border-border px-1" max="1" min="0" onChange={(event) => onChange({ ...value, minCriticality: event.target.value ? Number(event.target.value) : undefined })} step=".1" type="number" value={value.minCriticality ?? ""} /></label><label className="flex items-center gap-1"><input checked={value.includeUnclassified ?? false} onChange={(event) => onChange({ ...value, includeUnclassified: event.target.checked || undefined })} type="checkbox" /><T k="threeA.includeUnclassified" /></label></div>
    <label className="flex items-center gap-2 text-xs text-muted"><T k="threeA.mapKinds" /><select className="h-8 min-w-[15rem] rounded-md border border-border px-2" multiple onChange={(event) => onChange({ ...value, kinds: [...event.target.selectedOptions].map((option) => option.value as ArchitectureUnitKind) })} value={(value.kinds ?? []) as string[]}>{kinds.map((kind) => <option key={kind} value={kind}>{kind}</option>)}</select></label>
  </div>;
}
