"use client";

import { ChevronRight } from "lucide-react";
import { T } from "../language-provider";
import type { ThreeACoverageReport } from "../../lib/3a/workspace-loader";

export function CoverageDetail({ rows }: { rows: ThreeACoverageReport["rows"] }) {
  return <section className="rounded-lg border border-border bg-white p-4 shadow-panel" data-testid="coverage-detail"><div className="flex items-center justify-between gap-3"><h3 className="text-sm font-semibold text-ink"><T k="threeA.assetMappingDetail" /></h3><span className="text-xs text-muted"><T k="threeA.coverageBounded" /></span></div><div className="mt-3 divide-y divide-border">{rows.length ? rows.map((row) => { const mode = row.status === "BLOCKED" || row.status === "NOT_EVALUATED" ? "BLOCKED" : row.role === "MEMBERSHIP" ? "DIRECT" : row.role === "EXEMPTION" ? "EXEMPT" : "TRACE"; return <div key={`${row.assetType}:${row.assetId}`} className="grid gap-2 py-3 md:grid-cols-[minmax(0,1fr)_100px_110px_minmax(0,1.4fr)] md:items-center"><div className="min-w-0"><p className="truncate font-mono text-xs text-ink">{row.assetId}</p><p className="text-xs text-muted">{row.assetType}</p></div><span className={`text-xs font-semibold ${mode === "DIRECT" ? "text-emerald-700" : mode === "TRACE" ? "text-blue-700" : mode === "BLOCKED" ? "text-rose-700" : "text-amber-700"}`}>{mode}</span><span className={`text-xs font-semibold ${row.status === "COVERED" ? "text-emerald-700" : row.status === "BLOCKED" ? "text-rose-700" : "text-amber-700"}`}>{row.status}</span><div className="flex min-w-0 items-center gap-1 text-xs text-muted">{row.reasonCode ? <span className="truncate">{row.reasonCode}</span> : row.terminalMemberId ? <><span className="truncate">{row.terminalMemberId}</span><ChevronRight size={13} /></> : <T k="threeA.coverageNoPath" />}</div></div>; }) : <div className="py-8 text-center text-sm text-muted"><T k="threeA.coverageEmpty" /></div>}</div></section>;
}
